import { MigrationInterface, QueryRunner } from "typeorm";

export class Entitytextfix1697108196074 implements MigrationInterface {
    name = 'Entitytextfix1697108196074'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`pages_extra\` DROP FOREIGN KEY \`fk_pages_extra_author_id\``);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`author_id\` \`author_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`title\` \`title\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`excerpt\` \`excerpt\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`body\` \`body\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`image\` \`image\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`meta_description\` \`meta_description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`meta_keywords\` \`meta_keywords\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`textimage\` \`textimage\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`breadimage\` \`breadimage\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`titlesmall\` \`titlesmall\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`title\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`excerpt\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`excerpt\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`body\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`body\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`image\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`image\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`meta_description\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`meta_description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`meta_keywords\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`meta_keywords\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`textimage\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`textimage\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`titlesmall\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`titlesmall\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`img\` \`img\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`img_type\` \`img_type\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`blogs\` DROP COLUMN \`excerpt\``);
        await queryRunner.query(`ALTER TABLE \`blogs\` ADD \`excerpt\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`blogs\` DROP COLUMN \`body\``);
        await queryRunner.query(`ALTER TABLE \`blogs\` ADD \`body\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`blogs\` CHANGE \`img\` \`img\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`blogs\` DROP COLUMN \`meta_description\``);
        await queryRunner.query(`ALTER TABLE \`blogs\` ADD \`meta_description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`blogs\` DROP COLUMN \`meta_keywords\``);
        await queryRunner.query(`ALTER TABLE \`blogs\` ADD \`meta_keywords\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`generals\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`generals\` ADD \`title\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`generals\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`generals\` ADD \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`generals\` CHANGE \`img\` \`img\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`generals\` CHANGE \`button\` \`button\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`generals\` CHANGE \`href\` \`href\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP FOREIGN KEY \`fk_m_menu_belong_id\``);
        await queryRunner.query(`ALTER TABLE \`menu\` CHANGE \`menu_belong_id\` \`menu_belong_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`menu\` CHANGE \`page_belongs\` \`page_belongs\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`menu\` CHANGE \`route\` \`route\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`sliders\` DROP COLUMN \`stext\``);
        await queryRunner.query(`ALTER TABLE \`sliders\` ADD \`stext\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`sliders\` DROP COLUMN \`simg\``);
        await queryRunner.query(`ALTER TABLE \`sliders\` ADD \`simg\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` ADD CONSTRAINT \`fk_pages_extra_author_id\` FOREIGN KEY (\`author_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD CONSTRAINT \`fk_m_menu_belong_id\` FOREIGN KEY (\`menu_belong_id\`) REFERENCES \`menu\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`menu\` DROP FOREIGN KEY \`fk_m_menu_belong_id\``);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` DROP FOREIGN KEY \`fk_pages_extra_author_id\``);
        await queryRunner.query(`ALTER TABLE \`sliders\` DROP COLUMN \`simg\``);
        await queryRunner.query(`ALTER TABLE \`sliders\` ADD \`simg\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sliders\` DROP COLUMN \`stext\``);
        await queryRunner.query(`ALTER TABLE \`sliders\` ADD \`stext\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`menu\` CHANGE \`route\` \`route\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu\` CHANGE \`page_belongs\` \`page_belongs\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu\` CHANGE \`menu_belong_id\` \`menu_belong_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD CONSTRAINT \`fk_m_menu_belong_id\` FOREIGN KEY (\`menu_belong_id\`) REFERENCES \`menu\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`generals\` CHANGE \`href\` \`href\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`generals\` CHANGE \`button\` \`button\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`generals\` CHANGE \`img\` \`img\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`generals\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`generals\` ADD \`description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`generals\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`generals\` ADD \`title\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blogs\` DROP COLUMN \`meta_keywords\``);
        await queryRunner.query(`ALTER TABLE \`blogs\` ADD \`meta_keywords\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blogs\` DROP COLUMN \`meta_description\``);
        await queryRunner.query(`ALTER TABLE \`blogs\` ADD \`meta_description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blogs\` CHANGE \`img\` \`img\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`blogs\` DROP COLUMN \`body\``);
        await queryRunner.query(`ALTER TABLE \`blogs\` ADD \`body\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blogs\` DROP COLUMN \`excerpt\``);
        await queryRunner.query(`ALTER TABLE \`blogs\` ADD \`excerpt\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`img_type\` \`img_type\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`img\` \`img\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`titlesmall\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`titlesmall\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`textimage\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`textimage\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`meta_keywords\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`meta_keywords\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`meta_description\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`meta_description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`image\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`image\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`body\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`body\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`excerpt\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`excerpt\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD \`title\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`titlesmall\` \`titlesmall\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`breadimage\` \`breadimage\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`textimage\` \`textimage\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`meta_keywords\` \`meta_keywords\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`meta_description\` \`meta_description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`image\` \`image\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`body\` \`body\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`excerpt\` \`excerpt\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`title\` \`title\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` CHANGE \`author_id\` \`author_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages_extra\` ADD CONSTRAINT \`fk_pages_extra_author_id\` FOREIGN KEY (\`author_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
